version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "America/New_York"
    labels: []
    commit-message:
      prefix: "deps(pnpm)"
    groups:
      pnpm:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/workers/raweb-install-worker"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "America/New_York"
    labels: []
    commit-message:
      prefix: "deps(raweb-install-worker)"
    groups:
      pnpm:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/.github/actions/test-android-windows-app/appium"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "America/New_York"
    labels: []
    commit-message:
      prefix: "deps(appium)"
    groups:
      pnpm:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/dotnet"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "08:00"
      timezone: "America/New_York"
    labels: []
    commit-message:
      prefix: "deps(nuget)"
    groups:
      nuget:
        patterns:
          - "*"

    # we want daily updates for dotnet's sdk because
    # sdk updates typically completely break the builds
    # due to new mismatches in the lockfiles
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "America/New_York"
    labels: []
    commit-message:
      prefix: "deps(dotnet)"
